import math,cmath,statistics,decimal,random,fractions,itertools,numpy as np,sympy as sp,mpmath as mp
pi=math.pi
def sqrt(x):return math.sqrt(x)
def ln(x):return math.ln(x)
def log(x,a):return math.log(x,a)
def abs(x):return abs(x)
def sin(x):return math.sin(x)
def cos(x):return math.cos(x)
def tan(x):return math.tan(x)
def asin(x):return math.asin(x)
def acos(x):return math.acos(x)
def atan(x):return math.atan(x)
def csc(x):return 1/math.sin(x)
def sec(x):return 1/math.cos(x)
def cot(x):return 1/math.tan(x)
def acsc(x):return math.asin(1/x)
def asec(x):return math.acos(1/x)
def acot(x):return pi-math.atan(x)
def sinh(x):return math.sinh(x)
def cosh(x):return math.cosh(x)
def tanh(x):return math.tanh(x)
def asinh(x):return math.asinh(x)
def acosh(x):return math.acosh(x)
def atanh(x):return math.atanh(x)
def dsin(x):x=pi*x/180;return math.sin(x)
def dcos(x):x=pi*x/180;return math.cos(x)
def dtan(x):x=pi*x/180;return math.tan(x)
def dasin(x):x=pi*x/180;return math.asin(x)
def dacos(x):x=pi*x/180;return math.acos(x)
def datan(x):x=pi*x/180;return math.atan(x)
def dsinh(x):x=pi*x/180;return math.sinh(x)
def dcosh(x):x=pi*x/180;return math.cosh(x)
def dtanh(x):x=pi*x/180;return math.tanh(x)
def dasinh(x):x=pi*x/180;return math.asinh(x)
def dacosh(x):x=pi*x/180;return math.acosh(x)
def datanh(x):x=pi*x/180;return math.atanh(x)
def dcsc(x):x=pi*x/180;return 1/math.sin(x)
def dsec(x):x=pi*x/180;return 1/math.cos(x)
def dcot(x):x=pi*x/180;return 1/math.tan(x)
def dacsc(x):x=pi*x/180;return math.asin(1/x)
def dasec(x):x=pi*x/180;return math.acos(1/x)
def dacot(x):x=pi*x/180;return pi-math.atan(x)
'eof'
def gamma(x):return math.gamma(x)
def fact(x):return math.gamma(x+1)
def nPr(n,k):return math.perm(n,k)
def nCr(n,k):return math.comb(n,k)
def mean(*A):A=tuple(B for A in A for B in(A if isinstance(A,list)else[A]));return statistics.mean(A)
def stdev(*A):A=tuple(B for A in A for B in(A if isinstance(A,list)else[A]));return statistics.stdev(A)
def stdevp(*A):A=tuple(B for A in A for B in(A if isinstance(A,list)else[A]));return statistics.pstdev(A)
def erf(x):return math.erf(x)
def erfc(x):return math.erfc(x)